### PR TITLE
Issue 720 no db indices

### LINKED ISSUE #720: Add option to exclude indices from being created for history tables
**Problem Statement**
We have some rather large tables where we use django-simple-history. The total size of the history tables is quite large but also the indices created. We do not use (most of) the indexes in the history table. It would be great if we could exclude them from being created.

This will save performance while updating the history table but especially will save us disk space. Expected disk space to be saved in our case would be over 30Gb.

**Describe the solution you'd like**
An option to exclude indices like we exclude fields. Not sure what best solution would be.

**Describe alternatives you've considered**
None.

**Additional context**
NA.

### PR DESCRIPTION
**Pull request by Sult**
Based on this ticket:
This fixes #720

# Motivation
As a company we could really use a feature like this. Rather include it in the official package, so others can use this as well. Instead of making our own fork.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have run the `make format` command to format my code
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] I have added my name and/or github handle to `AUTHORS.rst`
- [x] I have added my change to `CHANGES.rst`
- [x] All new and existing tests passed.

TODO: 
- make sure it all runs with tox. having some issues trying local
- have not used make format yet
- Not sure if i also should include a test to make sure the register method picks this up correctly (Tested manually)

### CODE REVIEW

**Comment by Sult** [comment]
I cant seem to be able to reach the Codecov location to see what i missed.
getting: upstream connect error or disconnect/reset before headers. reset reason: local reset

**Comment by Sult** [comment]
Can someone explain to me why mariadb tests are failing? Do the have some db_index requirements or something?

**Review by jeking3 — CHANGES_REQUESTED** [review]
I appreciate that even the conversion of single entry to list was unit tested; I am rejecting this because it needs to be rebased and the CHANGELOG needs to be fixed up, and it needs another CI run due to recent changes.  Other than that, this looks good.

**Comment by Sult** [comment]
Will update soon

**Comment by Sult** [comment]
@jeking3  I updated the PR. I hope this is what you meant :) If its really needed, I could re-base on master instead of having merged master into my branch.
Am at work so took the fast approach xD

**Comment by jeking3** [comment]
@Sult Yes you might want to do that since none of the CI seems to have run.

**Comment by wrvdklooster** [comment]
@Sult Do you have time to finish this one?

**Review by jeking3 — APPROVED** [review]

**Comment by jeking3** [comment]
Be sure to squash this one with GitHub as it goes in.

**Pull request merged**
