### PR TITLE
Use sync/async pattern for middleware since Django 3.1

### PR DESCRIPTION
**Pull request by john-parton**
Reworks the middleware so that it uses the recommended pattern in django docs for async/sync middleware.

## Description

Changed middleware to use pattern from docs: https://docs.djangoproject.com/en/4.2/topics/http/middleware/#asynchronous-support

## Motivation and Context
The current middleware is synchronous only. As Django is moving towards a more async capable stack, this puts the project inline with Django's goals.

## How Has This Been Tested?
Didn't. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have run the `pre-commit run` command to format and lint.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] I have added my name and/or github handle to `AUTHORS.rst`
- [ ] I have added my change to `CHANGES.rst`
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ddabble** [comment]
@john-parton Nice! What do you think about rewriting it so that `HistoryRequestMiddleware` remains class-based? I think that would be preferable, due to the increased flexibility class-based middleware provides, and to remove any potential confusion caused by the class-like naming of the function you committed (I do understand why you kept the name unchanged, though).

I'm planning on making it class-based myself if I don't receive any response within a week or so 🙂

**Comment by john-parton** [comment]
It's surprisingly difficult to properly subclass a middleware that offers both sync and async functionality. I think it probably just presents a foot-gun. I can't think of any use-case which subclasses such a simple middleware. Any customization I think would be done by layering a different middleware before or after it.

If you give me some actual use-case, I can refactor it, otherwise you're welcome to do so.

**Comment by ddabble** [comment]
Hm yeah, good points. I also happened to find [this example](https://code.djangoproject.com/ticket/34328#comment:11), illustrating some additional downsides.

**Comment by ddabble** [comment]
#1188 has already received an approval and will probably be merged within a week or so, which will lead to conflicts in this PR. I can post a comment here when it's merged, if you'd like to resolve those conflicts; otherwise, I can just do it myself and then merge 🙂

**Comment by john-parton** [comment]
Yeah, let me know when it's merged. I can take a crack at it.

**Comment by ddabble** [comment]
@john-parton It's been merged now :)

**Comment by john-parton** [comment]
@ddabble Updated. I originally just had the logic copy/pasted in the sync and async versions, but that was nasty, so I encapsulated the setting and deleting of the property with a helper.

**Review by ddabble — APPROVED** [review]
Looks good, thank you! 😊

**Pull request merged**
