### PR TITLE
Prepare for release 3.7.0

### PR DESCRIPTION
**Pull request by ddabble**
## Description

Added a `3.7.0` version section to `CHANGES.rst`, and moved the PyPI readme comments (695b17f626ca15d458a7c884833ac107ffd941ca).

Also replaced the PyPI readme comments in `CHANGES.rst` with a regex in `pyproject.toml`, to avoid having to move the comments *every* time we're preparing a new release (1fe70ab41c3add16cc1752929cbd8aee8d08c42b).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have run the `pre-commit run` command to format and lint.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] I have added my name and/or github handle to `AUTHORS.rst`
- [x] I have added my change to `CHANGES.rst`
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ddabble** [comment]
@tim-schilling Any thoughts on replacing the PyPI readme comments with a somewhat complex regex (in 1fe70ab41c3add16cc1752929cbd8aee8d08c42b)? 🙂

**Comment by tim-schilling** [comment]
> somewhat complex regex

Somewhat eh? :sweat_smile: 

I think I'm good with it. If it doesn't work, it's a small problem and doesn't impact the library as a whole. I say to that to mean the risk is fairly low.

**Review by tim-schilling — APPROVED** [review]

**Comment by ddabble** [comment]
> Somewhat eh? 😅

Hahah, I've seen too many regexes horrifyingly more complex than this one, so it's sometimes challenging to judge the complexity when I know those exist 😅

> I think I'm good with it. If it doesn't work, it's a small problem and doesn't impact the library as a whole. I say to that to mean the risk is fairly low.

I agree :) Worst-case, the PyPI readme will contain parts of the Unreleased section, or the changelog won't be included at all - both of which I think are *acceptable*, since the unaltered changelog is present in both the docs and on GitHub (which are also linked to from PyPI).

**Comment by ddabble** [comment]
@treyhunner Would you mind publishing the newest version to PyPI, again? :)

**Comment by treyhunner** [comment]
> @treyhunner Would you mind publishing the newest version to PyPI, again? :)

Published 👍

**Pull request merged**
