### PR TITLE
History view pagination

### PR DESCRIPTION
**Pull request by jurrian**
## Description

This will add pagination and filtering to the simple history admin view. This is needed because it will allow more performance views on instances with many historical records. Currently it is very likely to timeout depending on the settings.

It uses the same pagination as the default in Django.

## Related Issue
This PR replaces this stale PR: https://github.com/jazzband/django-simple-history/pull/1220
Most of the text of this PR is copied from the stale one.

Closes https://github.com/jazzband/django-simple-history/issues/1117 and closes https://github.com/jazzband/django-simple-history/issues/1219.

## Motivation and Context

This is needed because it will allow more performance views on instances with many historical records. Currently it is very likely to timeout depending on the settings .

## How Has This Been Tested?

Added a few extra tests on top of what already existed in the stale PR.

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have run the `pre-commit run` command to format and lint.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] I have added my name and/or github handle to `AUTHORS.rst`
- [x] I have added my change to `CHANGES.rst`
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jurrian** [comment]
@ddabble could you have a look at this? It's basically the same as #1220 that you reviewed, with a small addition to make it work.

**Comment by diogosilva30** [comment]
Any update on this? Do you need any help?

**Comment by jurrian** [comment]
@ddabble ?

**Comment by ddabble** [comment]
@jurrian Sorry for the late reply; I'm busy with some of the other PRs, currently, but this is definitely on my TODO list 🙂

**Comment by ferran-gutierrez** [comment]
Hi guys!

How is going this feature?  I'm super engaged with that, for us would be an amazing deliveryHi guys!

How is going this feature?  I'm super engaged with that for us will be an amazing delivery

**Comment by jurrian** [comment]
Only needs review at the moment. Code should be complete, but needs to be tested and merged.

**Review by tim-schilling — DISMISSED** [review]
This looks good to me. It seems like it's a bit old now and needs to be rebased on main. Is that something you may have time for yet?

**Comment by jurrian** [comment]
@tim-schilling I have done the rebase and did some minor tweaks. Most notably `historical_records` is now `page_obj` to avoid confusion about the object. I tried to keep it in line with the Django [docs](https://docs.djangoproject.com/en/5.1/topics/pagination/) and `django/contrib/admin/templates/admin/object_history.html` template.

**Review by tim-schilling — APPROVED** [review]
This looks good to me! Thank you @jurrian!

**Pull request merged**
