### PR TITLE
Fix: Error when setting table name with inherit

### LINKED ISSUE #1195: Error when setting table_name with inherit=True
**Problem Statement**

When `table_name` is set with `inherit=True` in base model then error is thrown when `makemigrations` command is entered.

***For example:***

```
from django.db import models
from simple_history.models import HistoricalRecords

class BaseModel(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    last_updated_date = models.DateTimeField(auto_now=True)
    history = HistoricalRecords(inherit=True, table_name='base_model_history')
  
class ChildModel(BaseModel):
    title = models.CharField(max_length=255, blank=False, null=False)

```    
***Following error is thrown with above code:***

(models.E028) db_table 'base_model_history' is used by multiple models: inherit.HistoricalBaseModel, inherit.HistoricalChildModel.

**Describe the solution you'd like**

***Cause of Problem***

As per my understanding, after looking at the source code, I found that `Meta.db_table` property of model is updated when `table_name` property is set. In case, when `inherit=True`, `self.table_name` still points to `table_name ` set in the base model when `create_history_model `method is invoked for the child model. This logic is implemented in line 301-302 in [create_history_model ](https://github.com/jazzband/django-simple-history/blob/master/simple_history/models.py) method.

***Possible Solution***

inherited flag is sent as an argument to `create_history_model` method, this can be used in the condition where table_name is checked. Condition at line 301 will look like this:
`if not inherited and self.table_name is not None:`

If it can not be done, then this behavior should be mentioned explicitly in the documentation.

**Describe alternatives you've considered**

Overridden `create_history_model` method to update `table_name` when inherited is set to True and table_name is set:

```
from django.db import models
from simple_history.models import HistoricalRecords


class CustomHistoricalRecords(HistoricalRecords):
    def create_history_model(self, model, inherited):
        if inherited and self.table_name:
            self.table_name=f"{model._meta.app_label}_{self.get_history_model_name(model)}"
        history_model = super().create_history_model(model, inherited)
        return history_model

class BaseModel(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    last_updated_date = models.DateTimeField(auto_now=True)
    history = CustomHistoricalRecords(inherit=True, table_name="base_model_history")
  
class ChildModel(BaseModel):
    title = models.CharField(max_length=255, blank=False, null=False)
```

**Additional context**

I found this issue while looking for the solution of  #1174

### PR DESCRIPTION
**Pull request by muneeb706**
Error was thrown when `table_name` is set with inherit=True in base model.
inherited check added in the condition where `table_name` is checked for updating db table name. 

## Description

inherited flag argument in `create_history_model` method is used in the condition where `table_name` is checked. Condition at line 301 of `simple_history.models` now look like this:
`if not inherited and self.table_name is not None:`

## Related Issue
Closes #1195.

## Motivation and Context
I found this issue while looking for the solution of #1174.
In documentation it is not mentioned that table_name can't be used with inherit. It is implied that this should work, this inconsistency was the motivation.

## How Has This Been Tested?
Ran tests locally using `runtests.py`  with python (3.8,3.11) and django 4.1

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have run the `pre-commit run` command to format and lint.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] I have added my name and/or github handle to `AUTHORS.rst`
- [x] I have added my change to `CHANGES.rst`
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by theryanwalker — COMMENTED** [review]
Looks good to me! It would be great to have a test for this fix.

**Comment by muneeb706** [comment]
> Looks good to me! It would be great to have a test for this fix.

Thank you for reviewing, I have added a test.

**Review by theryanwalker — APPROVED** [review]
LGTM, thanks for the test @muneeb706!

**Review by ddabble — APPROVED** [review]
Looks good! Thank you, @muneeb706, and also @theryanwalker for reviewing :)

**Pull request merged**
