### PR TITLE
Add ignore_conflicts to bulk_create_with_history

### PR DESCRIPTION
**Pull request by shihanng**
## Description

If we are to support `ignore_conflicts`, we need to consider that not all item in the list of objects will be bulk created due to conflicts. Then, we also need to make sure that we create history records only for those objects that we created successfully. Unfortunately, we can't rely on the return value of `bulk_create` API because it returns all objects including those it ignores. Therefore, whenever `ignore_conflicts=True` we need to "force" the second transaction to query the created objects.

## Related Issue

Close https://github.com/jazzband/django-simple-history/issues/732

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have run the `make format` command to format my code
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] I have added my name and/or github handle to `AUTHORS.rst`
- [x] I have added my change to `CHANGES.rst`
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by shihanng** [comment]
Hi, I am opening this PR to propose a solution to #732. Please take a look and let me know what you think? Thank you.

**Comment by ThePumpingLemma** [comment]
@shihanng would you mind rebasing? Think it looks good otherwise but I'll let @rossmechanic chime in.

**Comment by shihanng** [comment]
@ThePumpingLemma, rebased. Thank you.

**Review by ThePumpingLemma — APPROVED** [review]
Thanks!

**Comment by ThePumpingLemma** [comment]
Not sure code climate is ever going to run. /shrug

**Pull request merged**
