### PR TITLE
feat(m2m-fields): allow to pass custom through M2M

### PR DESCRIPTION
**Pull request by antoineauger**
## Description

This MR is an attempt for allowing to pass a M2M model (possibly defined with `through`/`through_fields` attributes) to the `m2m_fields`.
The `ManyToManyField` model can be defined with `through` being either a string or a model instance. The `through_fields` can be a tuple of strings.

## Related Issue
Related https://github.com/jazzband/django-simple-history/issues/1094

Related https://github.com/jazzband/django-simple-history/pull/1093

## Motivation and Context
This MR is intended to allow the following to work:

```python
class PollWithManyToManyThroughFields(models.Model):
    question = models.CharField(max_length=200)
    people = models.ManyToManyField("Place", through="Venue", through_fields=("place", "guest"))

    history = HistoricalRecords(m2m_fields=[people])

class Venue(models.Model):
    place = models.ForeignKey("Place", on_delete=models.CASCADE, null=True)
    guest = models.ForeignKey("Person", on_delete=models.CASCADE, null=True)
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have run the `pre-commit run` command to format and lint.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] I have added my name and/or github handle to `AUTHORS.rst`
- [ ] I have added my change to `CHANGES.rst`
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by legau** [comment]
The `m2m_changed` signal tries to access the `Venue` model which is not yet initialized (lazy string notation). You have to find a way to make it connect at a later time

**Comment by lsmith77** [comment]
any chance to get this PR completed?

**Comment by antoineauger** [comment]
> any chance to get this PR completed?

@lsmith77 I kinda lack of Django knowledge regarding signals/lazy fields on my side to make any progress here, feel free to pick it up if you have an idea how to implement this 🙇🏻

**Comment by lsmith77** [comment]
a bummer .. I am a total Django newbie (and also still a Python beginner).

**Comment by antoineauger** [comment]
I couldn't find a way to make this work, I'll create an issue instead.

**Pull request closed without merging**
