### PR TITLE
Update Python and Django versions

### PR DESCRIPTION
**Pull request by ddabble**
### Highlights

- Dropped support for Python 3.7, which reached end-of-life on 2023-06-27 (4fd72f84a259662c3516ee4092dc69a5f8abd3d1)
- Dropped support for Django 4.0, which reached end-of-life on 2023-04-01 (83e3a0a275b514b5f0d93dfeec65750146bd145d)
- Added support for Django 4.2 (4e1ff900c6e5d763de8bf2dc43e16b9c7fcd018b, 8c67876ef2b87b87abe7b70ebf9f573482c6e1f1)

### Additional changes

- Added missing Python and Django versions to `tox.ini` and the docs (cf35f61ab5dd64c872cc521d60d2341a689af1a7, 5439c006b228fb86f3e0d5f4c0840f1277c8be3a)
- Simplified `envlist` in `tox.ini` (ca1d2c6aa6498438c9b4f486b48b925c87f91be3)
- Fixed missing `__version__` attribute (c7264e0f27d08be8f2db1d49444eef865525af8e)
- Added and cleaned up some URLs in `setup.py` and the docs (5c3141b1bee8cb9f15381dd32e70492ad3bd808f)

#### Fixing docs build

- Added `.readthedocs.yaml` to fix [a docs build failure](https://readthedocs.org/projects/django-simple-history/builds/21202330/) (92cb4b563664d6a447577f655377172ff6cdeeb4)
- In `requirements/docs.txt`, install this project in editable mode, to fix [another docs build failure](https://readthedocs.org/projects/ddabble-django-simple-history/builds/21202560/) (bd26f1906f2e2c50fd24be616a2252d0c8682a1c)

## How Has This Been Tested?

Through [GitHub Actions](https://github.com/jazzband/django-simple-history/actions/runs/5458716753).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have run the `pre-commit run` command to format and lint.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] I have added my name and/or github handle to `AUTHORS.rst`
- [x] I have added my change to `CHANGES.rst`
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by valberg** [comment]
Great work @ddabble! The docs build fails, but that might just be because it is not building from the correct repo.

**Review by valberg — APPROVED** [review]
Looks good to me! Good to get this moving :)

**Comment by ddabble** [comment]
Thanks, @valberg!

> The docs build fails, but that might just be because it is not building from the correct repo.

I suspected the same, so I tried building to a personal docs page, but got [a new error](https://readthedocs.org/projects/ddabble-django-simple-history/builds/21202560/).
I thought that this might have been because we now use `importlib.metadata` instead of `pkg_resources.get_distribution`, but building using the latter also resulted in [an error](https://readthedocs.org/projects/ddabble-django-simple-history/builds/21202891/).

However, I found out just now (from [this comment](https://stackoverflow.com/questions/75922593/sphinx-readthedocs-and-package-version#comment133915007_75923014)) that adding `-e .` on the last line of `requirements/docs.txt` lets the docs [build successfully](https://readthedocs.org/projects/ddabble-django-simple-history/builds/21202852/), though it makes me wonder how the docs have been built successfully until now 🤔

What do you think about adding `-e .` at the end of `docs.txt`?

**Comment by valberg** [comment]
@ddabble Give it a try and I'll approve it

**Comment by ddabble** [comment]
@valberg Alright, tests passed :)

**Review by valberg — APPROVED** [review]
Great! 👏

**Pull request merged**
