### PR TITLE
Prepare for 3.5.0 release

### PR DESCRIPTION
**Pull request by tim-schilling**
## Description

This is based off on #1289. I don't know how to chain PRs across repos in GitHub, so this may need to be cleaned up a bit. Or closed outright and redone.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have run the `pre-commit run` command to format and lint.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] I have added my name and/or github handle to `AUTHORS.rst`
- [x] I have added my change to `CHANGES.rst`
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tim-schilling** [comment]
@ddabble I merged a few dependency updates since they were pretty minimal. Hopefully that was alright by you. I updated the project for 5.0, dropped 4.1 in #1289. There's a bug fix from August that would be really helpful to my project so I wanted to help things along to make it easier for the next release. There looks to be a couple of other nice features since 3.4.0 as well.

**Comment by ddabble** [comment]
> I merged a few dependency updates since they were pretty minimal. Hopefully that was alright by you.

You're more than welcome to do so! Any help maintaining is greatly appreciated 😄

> I updated the project for 5.0, dropped 4.1 in #1289.

Nice, I'll take a look (and also check if there are more things from 5.0 this project could benefit from) once I have time, but I'm not sure I will before sometime after new year..

---

Btw, is it okay if I request reviews from you for some future PRs I have planned for this repo? 🙂

**Comment by tim-schilling** [comment]
> Btw, is it okay if I request reviews from you for some future PRs I have planned for this repo? 🙂

Yeah, feel free to request reviews from me in the future. I can't promise they'll be timely though 😁

**Comment by ddabble** [comment]
Great! 😊 

> I can't promise they'll be timely though 😁

No worries, and I guess I can also relate to that 😅

**Comment by ddabble** [comment]
> This is based off on #1289. I don't know how to chain PRs across repos in GitHub, so this may need to be cleaned up a bit. Or closed outright and redone.

I rebased on `master`, so it's good 🙂 But yeah, the usual method of setting the base branch to the branch of the PR you're basing it off, doesn't really work across repos, it seems 🤔

**Comment by tim-schilling** [comment]
Not a big deal. Next time if I want to do that, I'll create the branches on the repo.

**Review by ddabble — APPROVED** [review]

**Comment by treyhunner** [comment]
> @treyhunner @rossmechanic Could one of you publish v3.5.0 to PyPI? 🙂

Done!

**Pull request merged**
