### PR TITLE
add support for verbose_name_plural

### PR DESCRIPTION
**Pull request by sridhar562345**
## Description

add a field verbose_name_plural

## Motivation and Context

This solves the problem of verbose name plural. 
Suppose, if we have a model named Country and if we register Country historical model to display in django admin, it displays model name as Historical Countrys, which is not desirable.

## How Has This Been Tested?

No other areas of code will be affected by this

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have run the `make format` command to format my code
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] I have added my name and/or github handle to `AUTHORS.rst`
- [ ] I have added my change to `CHANGES.rst`
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by jeking3 — COMMENTED** [review]
Does an existing test cover this code change?

**Comment by sridhar562345** [comment]
> Does an existing test cover this code change?
I don't think so, it will just update meta data of a model

**Comment by jeking3** [comment]
@sridhar562345 please consider adding a unit test for the new path.

**Comment by sridhar562345** [comment]
@jeking3 Added unit tests and tested.

**Review by jeking3 — APPROVED** [review]

**Pull request merged**
