### PR TITLE
Add release config.

### PR DESCRIPTION
**Pull request by jezdez**
## Description

This consolidates the tox and Travis-CI config into one, where the tox config is the single source of truth of what should be tested and how and the Travis-CI config the information for the test environment. The library [tox-travis](https://github.com/tox-dev/tox-travis) is used to bridge the two.

This pattern has shown to be better in the long term since it allows us to move elsewhere from Travis-CI (e.g. GitHub actions) when we need. Assuming you have all the Python versions installed this should also make running `tox` locally be close to the test environment.

The Travis-CI config now uses its [build stages](https://docs.travis-ci.com/user/build-stages/) to only ever run the release deployment (to Jazzband's package index) for one Python environment and not for the first one that happens to run in parallel. 

Note, this also enabled Jazzband releases via the "new" project leads @treyhunner and @rossmechanic as requested in #670. 

## Related Issue

#670

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have run the `make format` command to format my code
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] I have added my name and/or github handle to `AUTHORS.rst`
- [ ] I have added my change to `CHANGES.rst`
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jezdez** [comment]
I think the "djangotrunk" failures are legitimate issues with the current Django dev environment. Still trying to figure out why the others are failing..

**Comment by jezdez** [comment]
Hey all, this is passing now, I found the issue with the trunk tests, this was about https://github.com/django/django/pull/13207 breaking some assumptions when copying the historical model TextField and is passing now. Let me know if you have any questions about this, I'd appreciate a review so we can close #670.

**Review by rossmechanic — APPROVED** [review]
This all looks good to me! Thanks for getting to this @jezdez

**Comment by jezdez** [comment]
Thanks @rossmechanic!

**Comment by rossmechanic** [comment]
@jezdez looks like this broke docs (https://readthedocs.org/projects/django-simple-history/builds/12146335/) and now I'm seeing the invalid webhook there again.

**Comment by jezdez** [comment]
@rossmechanic Okay, I switched over to finding the version using pkg_resources instead of a file that is written during installation and updated the RTD config to install the project during docs build-time as well. The last build log showed it passes now..

**Comment by jezdez** [comment]
And I just fixed the two black issues as well..

**Comment by rossmechanic** [comment]
Ha - was just going to mention them. Thanks for all the help here @jezdez

**Pull request merged**
