### PR TITLE
Drop support for Django 3.2

### PR DESCRIPTION
**Pull request by ddabble**
## Description

Django 3.2's EOL was passed last month (April 1st); see [Django's supported versions](https://www.djangoproject.com/download/#supported-versions).

## Related Issue

None

## Motivation and Context

Removing support for dependencies for which development has stopped.

## How Has This Been Tested?

See the GitHub Actions test build.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have run the `pre-commit run` command to format and lint.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] I have added my name and/or github handle to `AUTHORS.rst`
- [x] I have added my change to `CHANGES.rst`
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ddabble** [comment]
@tim-schilling Are you available to review this? I'm planning on opening a release PR after merging this 🙂

**Comment by tim-schilling** [comment]
I'll to try to make time tomorrow morning, but no promises. Feel free to merge and release without it though!

**Comment by ddabble** [comment]
Great! No worries if it turns out otherwise :)

I don't have the administrative permissions to merge without a review (assuming that's what you meant), but I can try requesting reviews from some of the other Jazzband members 🙂

**Review by tim-schilling — DISMISSED** [review]
Looks good!

If you have time, I'd suggest doing two releases. The first with all of the changes before dropping 3.2. Then another version that drops 3.2. That way anyone using 3.2 still can utilize the latest changes.

Though then again, it's a lot easier to just release it all together 😄

**Comment by ddabble** [comment]
> If you have time, I'd suggest doing two releases. The first with all of the changes before dropping 3.2. Then another version that drops 3.2. That way anyone using 3.2 still can utilize the latest changes.

Nice thinking, let's do that! I'll open a release PR for 3.6.0 before merging this 🙂

We can do 3.7.0 (or 3.6.1? 4.0.0? The version history's relationship with semantic versioning seems slightly inconsistent 😅) with the changes from this PR - though I'm not sure that I see the usefulness of a release that _only_ drops a dependency version used in our CI code..? 🤔 (..apart from removing the `asgiref>=3.6` installation requirement, I guess)

**Comment by tim-schilling** [comment]
Eh, I think minor version changes are fine for both, so 3.7.

**Review by tim-schilling — APPROVED** [review]

**Pull request merged**
